version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql_test_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATASOURCE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - arlabel_vol:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  arlabel_vol:
    driver: local