spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  port: ${SERVER_PORT}

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jackson:
    time-zone: Asia/Seoul

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  port: ${SERVER_PORT}

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  port: ${SERVER_PORT}